### ISSUE TITLE
Chapter 12 Q5

### ISSUE THREAD

**Issue by RoccoMathijn** [adrianwong/programming-in-haskell-2nd-edition#1]
https://github.com/adrianwong/programming-in-haskell-2nd-edition/blob/311422610be05210315ff113417f8605b1380a3c/ch12_solutions.hs#L53

Hi Adrian, 

I'm not quite sure but shouldn't this be:
`(>>=) f g = \r -> g (f r)`

**Comment by RoccoMathijn** [comment]
Nope never mind. My bad.

**Comment by adrianwong** [comment]
No worries Rocco, keep the questions coming!

I'm not sure my answers for Ch12, Q7 and Q8 are correct, so feel free to dispute them if you think my solutions are incorrect.
